#fontName=fonts/truetype/freefont/FreeSans.ttf
fontName=fonts/TTF/luximb.ttf
#fontName=fonts/arialbd.ttf
dataDirectory=~/LiveViewData
databaseDirectory=~/LiveViewData/database
NMEADirectory=~/LiveViewData/NMEA
# Sarjaportin tunnus (COM1 tai COM2)
#serialPortName=COM1
#serialPortName=/dev/ttys0
socketHost=localhost
socketPort=2222
# Lasketaanko aluksen suunta sen per‰kk‰isist‰ koordinaateista vai otetaanko se GPS:st‰ (false).
countedAngle=true
#countedAngle=false
# Onko pohjoinen aina ylh‰‰ll‰ kartassa (kartan tekstit ovat aina vaakasuorassa)
fixedNorth=false
#fixedNorth=true
# Onko aluksen ymp‰rill‰ oleva varokeh‰ kokoympyr‰ vai puoliympyr‰
fullZoneCircle=false
disableAudio=false
#disableAudio=true
# Antaako GPS maanopeuden kilometreissa tunnissa (vai solmuissa)
groundSpeedInKmh=false
#groundSpeedInKmh=true
#longitude=24.926798600
#latitude=60.128341900
#longitude=27.460233
#latitude=68.345916
#longitude=27.422
#latitude=68.6105
# Inkoo
#longitude=23.94762
#latitude=60.05024
# Hongisto
#longitude=25.38333
#latitude=60.78333
# Vantaa
#longitude=24.86603
#latitude=60.29361
# Saariselk‰
#longitude=27.56978
#latitude=68.24273
#longitude=27.4153
#latitude=69.0929
longitude=-71.05
latitude=42.33
altitude=2000.0
sceneryMode=false
#sceneryMode=true
testing=true
#testing=false
# suurin sallitty v‰li sekunneissa ratapisteiss‰
trackToleranceSecs=100
showTracks=true
trackTimeRate=50.0
#disableGPS=true
#writeImages=true
vesselModel=UH-1N.flt
numberVideos=0
idVendor=2334
idProduct=3
gpsUsbDeviceGuid=2c9c45c2-8e7d-4c08-a12d-816bbae722c0
garmin=true
