if "%CONFIG%" == "Debug" (
cl /c /MDd /Zi /nologo /W4 /WX- /Od /Ob0 /Oy- /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /D "_MBCS" /Gm- /EHsc /RTC1 /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fp"Debug\LiveView.pch" /Gd /TP /analyze- /errorReport:queue LiveView.cpp NMEA.cpp SerialStream.cpp SocketStream.cpp USBStream.cpp USBFinder.cpp common.cpp Datum.cpp Garmin.cpp PlaybackVideo.cpp
@if not ERRORLEVEL 0 goto end
link /OUT:"LiveView.exe" /INCREMENTAL /NOLOGO "osgEarthd.lib" "osgEarthFeaturesd.lib" "osgEarthUtild.lib" "osgEarthSymbologyd.lib" "osgEarthAnnotationd.lib" "osgd.lib" "osgDBd.lib" "osgUtild.lib" "osgViewerd.lib" "OpenThreadsd.lib" "ws2_32.lib" "winmm.lib" "wldap32.lib" "osgShadowd.lib" "libcurld.lib" "zlibd.lib" "osgWidgetd.lib" "gdal_i.lib" "osgSimd.lib" "osgTerraind.lib" "osgFXd.lib" "osgManipulatord.lib" "osgTextd.lib" "osgGAd.lib" "osgART_debug.lib" "glu32.lib" "opengl32.lib" "SetupAPI.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /MANIFEST /ALLOWISOLATION /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /DEBUG /SUBSYSTEM:CONSOLE /STACK:"10000000" /PGD:"d:\ht\Debug\LiveView.pgd" /TLBID:1 /DYNAMICBASE /NXCOMPAT /MACHINE:X86 /ERRORREPORT:QUEUE LiveView.obj NMEA.obj SerialStream.obj SocketStream.obj USBStream.obj USBFinder.obj common.obj Datum.obj Garmin.obj PlaybackVideo.obj
) else (
cl /c /nologo /W3 /WX- /O2 /Ob2 /Oy- /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_SCL_SECURE_NO_WARNINGS" /D "_CRT_SECURE_NO_DEPRECATE" /D "_MBCS" /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fp"LiveView.pch" /Gd /TP /analyze- /errorReport:queue LiveView.cpp NMEA.cpp SerialStream.cpp SocketStream.cpp USBStream.cpp USBFinder.cpp common.cpp Datum.cpp Garmin.cpp PlaybackVideo.cpp
@if not ERRORLEVEL 0 goto end
link /OUT:"LiveView.exe" /INCREMENTAL:NO /NOLOGO "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" "SetupAPI.lib" "osgEarth%OSG_SUFFIX%.lib" "osgEarthFeatures%OSG_SUFFIX%.lib" "osgEarthUtil%OSG_SUFFIX%.lib" "osgEarthSymbology%OSG_SUFFIX%.lib" "osgEarthAnnotation%OSG_SUFFIX%.lib" "osg%OSG_SUFFIX%.lib" "osgDB%OSG_SUFFIX%.lib" "osgUtil%OSG_SUFFIX%.lib" "osgViewer%OSG_SUFFIX%.lib" "OpenThreads%OSG_SUFFIX%.lib" "ws2_32.lib" "winmm.lib" "wldap32.lib" "osgShadow%OSG_SUFFIX%.lib" "libcurl%OSG_SUFFIX%.lib" "zlib%OSG_SUFFIX%.lib" "osgWidget%OSG_SUFFIX%.lib" "gdal_i.lib" "osgSim%OSG_SUFFIX%.lib" "osgTerrain%OSG_SUFFIX%.lib" "osgFX%OSG_SUFFIX%.lib" "osgManipulator%OSG_SUFFIX%.lib" "osgText%OSG_SUFFIX%.lib" "osgGA%OSG_SUFFIX%.lib" "osgART%OSGART_SUFFIX%.lib" "glu32.lib" "opengl32.lib" LiveView.obj NMEA.obj SerialStream.obj SocketStream.obj USBStream.obj USBFinder.obj common.obj Datum.obj Garmin.obj PlaybackVideo.obj /MANIFEST /ALLOWISOLATION /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /SUBSYSTEM:CONSOLE /STACK:"10000000" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"LiveView.lib" /MACHINE:X86 /ERRORREPORT:QUEUE
)
@if not ERRORLEVEL 0 goto end
mt -manifest LiveView.exe.manifest -outputresource:LiveView.exe
@if not ERRORLEVEL 0 goto end
dir LiveView.exe
call setup.cmd
:end
