@rem CMake: Advanced
@rem COLLADA_BOOST_FILESYSTEM_LIBRARY: D:/lm/3rdParty/x86/lib/libboost_filesystem-vc100-mt.lib
@rem COLLADA_BOOST_FILESYSTEM_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libboost_filesystem-vc100-mt-gd.lib
@rem COLLADA_BOOST_SYSTEM_LIBRARY: D:/lm/3rdParty/x86/lib/libboost_system-vc100-mt.lib
@rem COLLADA_BOOST_SYSTEM_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libboost_system-vc100-mt-gd.lib
@rem COLLADA_DYNAMIC_LIBRARY: D:/lm/3rdParty/x86/lib/libcollada14dom21.lib
@rem COLLADA_DYNAMIC_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libcollada14dom21-d.lib
@rem COLLADA_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem CURL_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem CURL_LIBRARY: D:/lm/3rdParty/x86/lib/libcurl.lib
@rem CURL_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libcurlD.lib
@rem DIRECTSHOW_STRMBASE_INCLUDE_DIRS: D:/lm/3rdParty/x86/include/directshow
@rem DIRECTSHOW_STRMBASE_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/strmbasd.lib
@rem DIRECTSHOW_STRMBASE_LIBRARY_RELEASE: D:/lm/3rdParty/x86/lib/strmbase.lib
@rem FREETYPE_INCLUDE_DIR_freetype2: D:/lm/3rdParty/x86/include/freetype
@rem FREETYPE_LIBRARY: D:/lm/3rdParty/x86/lib/freetype2311MT.lib
@rem FREETYPE_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/freetype2311MT_D.lib
@rem GDAL_INCLUDE_DIR: D:/lm/gdal/release-1600/include
@rem GDAL_LIBRARY: D:/lm/gdal/release-1600/lib/gdal_i.lib
@rem GDAL_LIBRARY_DEBUG: D:/lm/gdal/release-1600/lib/gdal_i.lib
@rem GIFLIB_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem GIFLIB_LIBRARY: D:/lm/3rdParty/x86/lib/giflib.lib
@rem GIFLIB_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/giflibd.lib
@rem GLUT_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem GLUT_LIBRARY: D:/lm/3rdParty/x86/lib/glut32.lib
@rem GLUT_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/glut32D.lib
@rem JPEG_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem JPEG_LIBRARY: D:/lm/3rdParty/x86/lib/jpeg.lib
@rem JPEG_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/jpegD.lib
@rem LIBXML2_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem LIBXML2_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libxml2.lib
@rem NVTT_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem NVTT_LIBRARY: D:/lm/3rdParty/x86/lib/nvtt.lib
@rem TIFF_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem TIFF_LIBRARY: D:/lm/3rdParty/x86/lib/libtiff_i.lib
@rem TIFF_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libtiff_i.lib
@rem ZLIB_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem ZLIB_LIBRARY: D:/lm/3rdParty/x86/lib/zlib.lib
@rem ZLIB_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/zlibd.lib
@rem PNG_INCLUDE_DIR: D:/lm/3rdParty/x86/include
@rem PNG_LIBRARY: D:/lm/3rdParty/x86/lib/libpng.lib
@rem PNG_LIBRARY_DEBUG: D:/lm/3rdParty/x86/lib/libpng.lib
@rem PNG_PNG_INCLUDE_DIR: D:/lm/3rdParty/x86/include
